matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    language: android
    android:
      components:
      - tools
      - platform-tools
      - tools
      - build-tools-26.0.0
      - android-26
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    addons:
      apt:
        sources: 
        packages:
        - oracle-java8-installer
        - oracle-java8-set-default
        - jq
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - android-sdk-license
    - Android SDK Platform 26
    - google-gdk-license-.+
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
- rm -rf $HOME/.gradle/caches/3.5/fileHashes/
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - node_modules
env:
  global:
  - JAVA_HOME=/usr/lib/jvm/java-8-oracle
before_install:
- openssl aes-256-cbc -K $encrypted_62f3167d5387_key -iv $encrypted_62f3167d5387_iv -in my-release-key.jks.enc -out my-release-key.jks -d
- export LANG=en_US.UTF-8
- nvm install 8
- npm install -g ionic cordova@6.5.0
- find ./src -type f -exec sed -i -e "s#\/api#$sed#g" {} \;
before_script: 
script:
- npm install
- chmod a+x ./travis/build-ios.sh ./travis/package-ios.sh ./travis/build-android.sh ./travis/package-android.sh
- mkdir ./www
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis/build-android.sh && ./travis/package-android.sh $storepass; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./travis/build-android.sh crosswalk && ./travis/package-android.sh $storepass crosswalk; fi
deploy:
  provider: releases
  api_key:
    secure: Jgiw6BkZunUbYzg/N6rCY6Lr4Umma5Z9Z9a7Y7bxFH6RCJG+vQPccVC30ArIyX1WiSoBcUpcr8K4Z47L7Gx1D1esBTWru+0rMLSWaYWy8rs53JBG/qRmKS7kddANeEO/3XOUikqXoOO6XNOixYt5wCF4d2EfjmnaljjAHaf2VgBOjmn9DnX+1/viFjKTuEoEvNxavQFCHRNA3Q5kjXz02ckIp8ZUR8nG4I8nln1Xa26HipakKqJvjkxbW38KGx/KMXbcOXsyG6ffn4TaQNBO9EoPoyti6gAOxE1azL5fcXMtLOTxYhBDJ7Y3xz0IZAGbahmuu8yRTa4AbzBPLDWqugODr6YjsTmzmU1k2VUoaRM3iPYs9ITUv+XBdgsp1aCUg/rqUng1n1PR1uSyN25n6jsOc34MS+GwTk4Hmv8k/mYYIgbfVm/cl/6VeM2/97SND68bPnKqsa7jW/ZJFD0rgd2aunY2DXWQiXHDs4smKbmlHxU8DVAKjgWSiCQ1pzwqg3QrHLMWKW9x+ONYJcQgJcCLSF0/E78dbcVTcxG2uqhjUrRnYHI6DCVn2ObS46x0+2d8lveBxT+JQ8+4hbAa1am4F/2Rnqh2v/ekDPNsJ3Q1Bqq+HT+Dz/eE4VcSsQuxpUEc+NrWzzc0ejz81hAkxAdnTsCTyG290VpcxtWEB2k=
  file_glob: true
  file: output/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
